# Generated by Django 3.2.8 on 2021-10-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_completedorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyorder',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='sellorder',
            name='is_completed',
        ),
    ]
